#include "args.h"
#include <sys/socket.h>
#include <asm-generic/socket.h>

/* ══════════════════════════════════════════════════════════════════════
   Named-constant tables
   ══════════════════════════════════════════════════════════════════════ */

static const NamedConst open_flags[] = {
    { O_RDONLY,   "O_RDONLY"   },
    { O_WRONLY,   "O_WRONLY"   },
    { O_RDWR,     "O_RDWR"     },
    { O_CREAT,    "O_CREAT"    },
    { O_TRUNC,    "O_TRUNC"    },
    { O_APPEND,   "O_APPEND"   },
    { O_NONBLOCK, "O_NONBLOCK" },
    { O_DSYNC,    "O_DSYNC"    },
    { O_CLOEXEC,  "O_CLOEXEC"  },
    { O_DIRECTORY,"O_DIRECTORY"},
    { O_NOFOLLOW, "O_NOFOLLOW" },
#ifdef O_NOATIME
    { O_NOATIME,  "O_NOATIME"  },
#endif
#ifdef O_PATH
    { O_PATH,     "O_PATH"     },
#endif
#ifdef O_TMPFILE
    { O_TMPFILE,  "O_TMPFILE"  },
#endif
    { 0, NULL }
};

static const NamedConst mode_flags[] = {
    { 0400, "S_IRUSR" }, { 0200, "S_IWUSR" }, { 0100, "S_IXUSR" },
    { 0040, "S_IRGRP" }, { 0020, "S_IWGRP" }, { 0010, "S_IXGRP" },
    { 0004, "S_IROTH" }, { 0002, "S_IWOTH" }, { 0001, "S_IXOTH" },
    { 0, NULL }
};

static const NamedConst mmap_prot[] = {
    { PROT_NONE,  "PROT_NONE"  },
    { PROT_READ,  "PROT_READ"  },
    { PROT_WRITE, "PROT_WRITE" },
    { PROT_EXEC,  "PROT_EXEC"  },
    { 0, NULL }
};

static const NamedConst mmap_flags[] = {
    { MAP_SHARED,     "MAP_SHARED"     },
    { MAP_PRIVATE,    "MAP_PRIVATE"    },
    { MAP_FIXED,      "MAP_FIXED"      },
    { MAP_ANONYMOUS,  "MAP_ANONYMOUS"  },
    { MAP_GROWSDOWN,  "MAP_GROWSDOWN"  },
    { MAP_DENYWRITE,  "MAP_DENYWRITE"  },
    { MAP_EXECUTABLE, "MAP_EXECUTABLE" },
    { MAP_LOCKED,     "MAP_LOCKED"     },
    { MAP_NORESERVE,  "MAP_NORESERVE"  },
    { MAP_POPULATE,   "MAP_POPULATE"   },
    { MAP_STACK,      "MAP_STACK"      },
    { 0, NULL }
};

static const NamedConst whence_vals[] = {
    { SEEK_SET, "SEEK_SET" },
    { SEEK_CUR, "SEEK_CUR" },
    { SEEK_END, "SEEK_END" },
    { 0, NULL }
};

static const NamedConst sig_vals[] = {
    { SIGHUP,  "SIGHUP"  }, { SIGINT,  "SIGINT"  }, { SIGQUIT, "SIGQUIT" },
    { SIGILL,  "SIGILL"  }, { SIGABRT, "SIGABRT" }, { SIGFPE,  "SIGFPE"  },
    { SIGKILL, "SIGKILL" }, { SIGSEGV, "SIGSEGV" }, { SIGPIPE, "SIGPIPE" },
    { SIGALRM, "SIGALRM" }, { SIGTERM, "SIGTERM" }, { SIGUSR1, "SIGUSR1" },
    { SIGUSR2, "SIGUSR2" }, { SIGCHLD, "SIGCHLD" }, { SIGCONT, "SIGCONT" },
    { SIGSTOP, "SIGSTOP" }, { SIGTSTP, "SIGTSTP" }, { SIGTTIN, "SIGTTIN" },
    { SIGTTOU, "SIGTTOU" },
    { 0, NULL }
};

static const NamedConst at_flags[] = {
    { AT_FDCWD,            "AT_FDCWD"            },
    { AT_SYMLINK_NOFOLLOW, "AT_SYMLINK_NOFOLLOW" },
    { AT_REMOVEDIR,        "AT_REMOVEDIR"        },
#ifdef AT_EMPTY_PATH
    { AT_EMPTY_PATH,       "AT_EMPTY_PATH"       },
#endif
    { 0, NULL }
};

static const NamedConst access_modes[] = {
    { F_OK, "F_OK" },
    { R_OK, "R_OK" },
    { W_OK, "W_OK" },
    { X_OK, "X_OK" },
    { 0, NULL }
};

static const NamedConst clone_flags[] = {
    { 0x00000100, "CLONE_VM"      },
    { 0x00000200, "CLONE_FS"      },
    { 0x00000400, "CLONE_FILES"   },
    { 0x00000800, "CLONE_SIGHAND" },
    { 0x00002000, "CLONE_PTRACE"  },
    { 0x00004000, "CLONE_VFORK"   },
    { 0x00008000, "CLONE_PARENT"  },
    { 0x00010000, "CLONE_THREAD"  },
    { 0x00020000, "CLONE_NEWNS"   },
    { 0x00100000, "CLONE_IO"      },
    { 0, NULL }
};

static const NamedConst msg_flags[] = {
    { MSG_OOB,          "MSG_OOB"       },
    { MSG_PEEK,         "MSG_PEEK"      },
    { MSG_DONTROUTE,    "MSG_DONTROUTE" },
    { MSG_CTRUNC,       "MSG_CTRUNC"    },
    { MSG_TRUNC,        "MSG_TRUNC"     },
    { MSG_DONTWAIT,     "MSG_DONTWAIT"  },
    { MSG_EOR,          "MSG_EOR"       },
    { MSG_WAITALL,      "MSG_WAITALL"   },
    { MSG_NOSIGNAL,     "MSG_NOSIGNAL"  },
    { MSG_ERRQUEUE,     "MSG_ERRQUEUE"  },
    { MSG_CONFIRM,      "MSG_CONFIRM"   },
    { MSG_MORE,         "MSG_MORE"      },
    { 0, NULL }
};

static const NamedConst shutdown_how[] = {
    { SHUT_RD,   "SHUT_RD"   },
    { SHUT_WR,   "SHUT_WR"   },
    { SHUT_RDWR, "SHUT_RDWR" },
    { 0, NULL }
};

static const NamedConst wait_flags[] = {
    { WNOHANG,    "WNOHANG"    },
    { WUNTRACED,  "WUNTRACED"  },
    { WCONTINUED, "WCONTINUED" },
    { WNOWAIT,    "WNOWAIT"    },
    { 0, NULL }
};


/* NETWORKING*/
/* --- SOME OF TABLES ARE AUTOGENERATED, TODO: parse headers for other tables --- */

static const NamedConst socket_domain[] = {
    { AF_UNIX,      "AF_UNIX"      },
    { AF_INET,      "AF_INET"      },
    { AF_INET6,     "AF_INET6"     },
    { AF_NETLINK,   "AF_NETLINK"   },
    { AF_PACKET,    "AF_PACKET"    },
    { 0, NULL }
};

static const NamedConst socket_type[] = {
    { SOCK_STREAM,    "SOCK_STREAM"    },
    { SOCK_DGRAM,     "SOCK_DGRAM"     },
    { SOCK_RAW,       "SOCK_RAW"       },
    { SOCK_SEQPACKET, "SOCK_SEQPACKET" },
    { SOCK_NONBLOCK,  "SOCK_NONBLOCK"  },
    { SOCK_CLOEXEC,   "SOCK_CLOEXEC"   },
    { 0, NULL }
};

static const NamedConst socket_proto[] = {
    { IPPROTO_TCP,  "IPPROTO_TCP"  },
    { IPPROTO_UDP,  "IPPROTO_UDP"  },
    { IPPROTO_RAW,  "IPPROTO_RAW"  },
    { IPPROTO_ICMP, "IPPROTO_ICMP" },
    { 0, NULL }
};

static const NamedConst sockopt_level[] = {
    { SOL_SOCKET, "SOL_SOCKET" },
    { IPPROTO_TCP, "IPPROTO_TCP" },
    { IPPROTO_IP,  "IPPROTO_IP"  },
    { IPPROTO_IPV6,"IPPROTO_IPV6"},
    { 0, NULL }
};

/* ══════════════════════════════════════════════════════════════════════
   Syscall descriptor table  (x86-64 numbers)
   Add entries here — zero code changes elsewhere.
   ══════════════════════════════════════════════════════════════════════ */

#define S   ARG_STR
#define I   ARG_INT
#define U   ARG_UINT
#define H   ARG_HEX
#define P   ARG_PTR
#define FD  ARG_FD
#define FL  ARG_FLAGS
#define EN  ARG_ENUM
#define OC  ARG_OCTAL
#define NN  ARG_NONE

/* --- memory & buffers --- */
#define BUF ARG_BUF
#define SZ  ARG_SIZET
#define SSZ ARG_SSIZET
#define OFF ARG_OFFSET

/* --- process & signals --- */
#define PID ARG_PID
#define SIG ARG_SIG
#define SS  ARG_SIGSET
#define SAC ARG_SIGACTION

/* --- time --- */
#define TS  ARG_TIMESPEC
#define TV  ARG_TIMEVAL
#define CID ARG_CLOCKID

/* --- filesystem --- */
#define PT  ARG_PATH
#define AFD ARG_ATFD
#define STB ARG_STATBUF
#define IOV ARG_IOVEC

/* --- networking --- */
#define SA  ARG_SOCKADDR
#define SAO ARG_SOCKADDR_OUT
#define SL  ARG_SOCKLEN
#define SD  ARG_SOCKDOM
#define ST  ARG_SOCKTYPE
#define SP  ARG_SOCKPROT
#define CM  ARG_CMSG


/* --- ioctl / mmap / misc --- */
#define IOR ARG_IOCTL_REQ
#define MP  ARG_MMAPPROT
#define MF  ARG_MMAPFLAGS
#define WH  ARG_WHENCE


#define A(k)          { .kind = (k), .consts = NULL }
#define AF(k, tbl)    { .kind = (k), .consts = (tbl) }




static const SyscallDesc syscall_table[] = {
/*  nr   name            argc  arg0                    arg1                    arg2                      arg3              arg4   arg5  */
  {  0, "read",          3, { A(FD),              A(BUF),                A(SZ)                                                        } },
  {  1, "write",         3, { A(FD),              A(BUF),                A(SZ)                                                        } },
  {  2, "open",          3, { A(S),               AF(FL, open_flags),    AF(OC, mode_flags)                                           } },
  {  3, "close",         1, { A(FD)                                                                                                    } },
  {  4, "stat",          2, { A(S),               A(P)                                                                                } },
  {  5, "fstat",         2, { A(FD),              A(P)                                                                                } },
  {  6, "lstat",         2, { A(S),               A(P)                                                                                } },
  {  7, "poll",          3, { A(P),               A(U),                  A(I)                                                         } },
  {  8, "lseek",         3, { A(FD),              A(OFF),                AF(EN, whence_vals)                                          } },
  {  9, "mmap",          6, { A(P),               A(SZ),                 AF(FL, mmap_prot),  AF(FL, mmap_flags),  A(I),    A(OFF)     } },
  { 10, "mprotect",      3, { A(P),               A(SZ),                 AF(FL, mmap_prot)                                            } },
  { 11, "munmap",        2, { A(P),               A(SZ)                                                                               } },
  { 12, "brk",           1, { A(P)                                                                                                    } },
  { 16, "ioctl",         3, { A(FD),              A(H),                  A(H)                                                         } },
  { 17, "pread64",       4, { A(FD),              A(BUF),                A(SZ),              A(OFF)                                   } },
  { 18, "pwrite64",      4, { A(FD),              A(BUF),                A(SZ),              A(OFF)                                   } },
  { 19, "readv",         3, { A(FD),              A(IOV),                A(I)                                                         } },
  { 20, "writev",        3, { A(FD),              A(IOV),                A(I)                                                         } },
  { 21, "access",        2, { A(S),               AF(FL, access_modes)                                                                } },
  { 22, "pipe",          1, { A(P)                                                                                                     } },
  { 32, "dup",           1, { A(FD)                                                                                                    } },
  { 33, "dup2",          2, { A(FD),              A(FD)                                                                                } },
  { 39, "getpid",        0, { { 0 }                                                                                                    } },
  { 41, "socket", 3,    { AF(SD, socket_domain), AF(ST, socket_type),    AF(SP, socket_proto)                                          } },
  { 42, "connect",       3, { A(FD),              {.kind=SA,  .arg_idx=2},                 A(SL)                                       } },
  { 43, "accept",        3, { A(FD),              {.kind=SAO, .arg_idx=2},                 A(SL)                                        } },
  { 44, "sendto",        6, { A(FD),              A(BUF),                A(SZ),           AF(FL, msg_flags),   A(SA),  A(SL)       } },
  { 45, "recvfrom",       6, { A(FD),              A(BUF),                A(SZ),                 AF(FL, msg_flags),   {.kind=SAO, .arg_idx=5}, A(SL)      } },
  { 46, "sendmsg",       3, { A(FD),              A(CM),                 AF(FL, msg_flags)                                            } },
  { 47, "recvmsg",       3, { A(FD),              A(CM),                 AF(FL, msg_flags)                                            } },
  { 48, "shutdown",      2, { A(FD),              AF(EN, shutdown_how)                                                                } },
  { 49, "bind",          3, { A(FD),              A(SA),                 A(SL)                                                        } },
  { 50, "listen",        2, { A(FD),              A(I)                                                                                } },
  { 51, "getsockname",   3, { A(FD),              {.kind=SAO, .arg_idx=2},                 A(SL)                                      } },
  { 52, "getpeername",   3, { A(FD),              {.kind=SAO, .arg_idx=2},                 A(SL)                                      } },
  { 53, "socketpair",    4, { A(SD),              A(ST),                 A(SP),              A(P)                                     } },
  { 54, "setsockopt",     5, { A(FD),              A(I),                  AF(EN, sockopt_level),           A(P),                  A(SL)                } },
  { 55, "getsockopt",     5, { A(FD),              A(I),                  AF(EN, sockopt_name_sol_socket), A(P),                  A(SL)                } },
  { 56, "clone",         5, { AF(FL, clone_flags), A(P),                 A(P),               A(P),                A(P)                } },
  { 57, "fork",          0, { { 0 }                                                                                                    } },
  { 58, "vfork",         0, { { 0 }                                                                                                    } },
  { 59, "execve",        3, { A(S),               A(P),                  A(P)                                                         } },
  { 60, "exit",          1, { A(I)                                                                                                     } },
  { 61, "wait4",         4, { A(PID),             A(P),                  AF(FL, wait_flags), A(P)                                     } },
  { 62, "kill",          2, { A(PID),             AF(EN, sig_vals)                                                                    } },
  { 72, "fcntl",         3, { A(FD),              A(I),                  A(I)                                                         } },
  { 74, "fsync",         1, { A(FD)                                                                                                    } },
  { 75, "fdatasync",     1, { A(FD)                                                                                                    } },
  { 76, "truncate",      2, { A(S),               A(OFF)                                                                              } },
  { 77, "ftruncate",     2, { A(FD),              A(OFF)                                                                              } },
  { 78, "getdents",      3, { A(FD),              A(P),                  A(U)                                                         } },
  { 79, "getcwd",        2, { A(P),               A(SZ)                                                                               } },
  { 80, "chdir",         1, { A(S)                                                                                                     } },
  { 81, "fchdir",        1, { A(FD)                                                                                                    } },
  { 82, "rename",        2, { A(S),               A(S)                                                                                } },
  { 83, "mkdir",         2, { A(S),               AF(OC, mode_flags)                                                                  } },
  { 84, "rmdir",         1, { A(S)                                                                                                     } },
  { 86, "link",          2, { A(S),               A(S)                                                                                } },
  { 87, "unlink",        1, { A(S)                                                                                                     } },
  { 88, "symlink",       2, { A(S),               A(S)                                                                                } },
  { 89, "readlink",      3, { A(S),               A(P),                  A(SZ)                                                        } },
  { 90, "chmod",         2, { A(S),               AF(OC, mode_flags)                                                                  } },
  { 91, "fchmod",        2, { A(FD),              AF(OC, mode_flags)                                                                  } },
  { 95, "umask",         1, { AF(OC, mode_flags)                                                                                       } },
  {102, "getuid",        0, { { 0 }                                                                                                    } },
  {104, "getgid",        0, { { 0 }                                                                                                    } },
  {217, "getdents64",    3, { A(FD),              A(P),                  A(SZ)                                                        } },
  {231, "exit_group",    1, { A(I)                                                                                                     } },
  {257, "openat",        4, { A(AFD),             A(S),                  AF(FL, open_flags), AF(OC, mode_flags)                       } },
  {258, "mkdirat",       3, { A(AFD),             A(S),                  AF(OC, mode_flags)                                           } },
  {260, "fchownat",      5, { A(AFD),             A(S),                  A(U),               A(U),                A(I)                } },
  {263, "unlinkat",      3, { A(AFD),             A(S),                  A(I)                                                         } },
  {264, "renameat",      4, { A(AFD),             A(S),                  A(AFD),             A(S)                                     } },
  {267, "readlinkat",    4, { A(AFD),             A(S),                  A(P),               A(SZ)                                    } },
  {268, "fchmodat",      3, { A(AFD),             A(S),                  AF(OC, mode_flags)                                           } },
  {269, "faccessat",     3, { A(AFD),             A(S),                  AF(FL, access_modes)                                         } },
  {292, "dup3",          3, { A(FD),              A(FD),                 AF(FL, open_flags)                                           } },
  {293, "pipe2",         2, { A(P),               AF(FL, open_flags)                                                                  } },
  {302, "prlimit64",     4, { A(PID),             A(I),                  A(P),               A(P)                                     } },
  {318, "getrandom",     3, { A(P),               A(SZ),                 A(I)                                                         } },
  {319, "memfd_create",  2, { A(S),               A(I)                                                                                } },
};

#undef S
#undef I
#undef U
#undef H
#undef P
#undef FD
#undef FL
#undef EN
#undef OC
#undef NN
#undef A
#undef AF

#define TABLE_SIZE  (sizeof(syscall_table) / sizeof(syscall_table[0]))

/* ══════════════════════════════════════════════════════════════════════
   Lookup
   ══════════════════════════════════════════════════════════════════════ */
const SyscallDesc *syscall_desc_find(long nr)
{
    /* Linear scan is fine for ~60 entries; replace with sorted bsearch
       if the table grows past a few hundred entries. */
    for (size_t i = 0; i < TABLE_SIZE; i++)
        if (syscall_table[i].nr == (int)nr)
            return &syscall_table[i];
    return NULL;
}

/* ══════════════════════════════════════════════════════════════════════
   Formatters
   ══════════════════════════════════════════════════════════════════════ */

/* Format a bitwise-OR flags value */
static void fmt_flags(char *buf, size_t sz,
                      unsigned long long val,
                      const NamedConst *consts)
{

    if (!consts) {
        snprintf(buf, sz, "%lld", (long long)(int)(unsigned int)val);
        return;
    }

    size_t pos = 0;
    unsigned long long remaining = val;
    bool first = true;

    for (const NamedConst *c = consts; c->name; c++) {
        if (c->value == 0) continue;
        if ((remaining & c->value) == (unsigned long long)c->value) {
            if (!first) {
                if (pos + 1 < sz) buf[pos++] = '|';
            }
            size_t len = strlen(c->name);
            if (pos + len + 1 < sz) {
                memcpy(buf + pos, c->name, len);
                pos += len;
            }
            remaining &= ~(unsigned long long)c->value;
            first = false;
        }
    }

    /* Leftover bits not covered by any named constant */
    if (remaining || first) {
        int written = snprintf(buf + pos, sz - pos,
                               first ? "0x%llx" : "|0x%llx", remaining);
        if (written > 0) pos += (size_t)written;
    }
    buf[pos < sz ? pos : sz - 1] = '\0';
}

/* Format an enum (exactly one named value).
 * `val` arrives as a zero-extended register value.  Many kernel constants
 * are negative ints sign-extended to 64 bits, but the register holds the
 * unsigned 32-bit pattern (e.g. AT_FDCWD=-100 → 0xffffff9c → 4294967196).
 * We therefore compare both the raw 64-bit value and its sign-extended
 * 32-bit interpretation against each table entry. */
static void fmt_enum(char *buf, size_t sz,
                     unsigned long long val,
                     const NamedConst *consts)
{
    if (!consts) {
        snprintf(buf, sz, "%lld", (long long)(int)(unsigned int)val);
        return;
    }

    long long sval   = (long long)val;
    long long sval32 = (long long)(int)(unsigned int)val; /* sign-extend low 32 bits */

    for (const NamedConst *c = consts; c->name; c++) {
        long long cval = (long long)c->value;
        if (sval == cval || sval32 == cval) {
            snprintf(buf, sz, "%s", c->name);
            return;
        }
    }
    snprintf(buf, sz, "%lld", sval32);
}

/* Public: format one argument */
void arg_format(char *buf, size_t sz,
                const ArgDesc *desc, unsigned long long val,
                pid_t tracee, const user_regs_struct *regs,
                bool is_exit)
{
    switch (desc->kind) {
    case ARG_NONE:
        buf[0] = '\0';
        break;

    case ARG_INT:
        snprintf(buf, sz, "%lld", (long long)val);
        break;

    case ARG_UINT:
        snprintf(buf, sz, "%llu", val);
        break;

    case ARG_HEX:
        snprintf(buf, sz, "0x%llx", val);
        break;

    case ARG_OCTAL:
        snprintf(buf, sz, "0%llo", val);
        break;

    case ARG_PTR:
        if (val == 0)
            snprintf(buf, sz, "NULL");
        else
            snprintf(buf, sz, "0x%llx", val);
        break;

    case ARG_FD:
        snprintf(buf, sz, "%lld", (long long)val);
        break;
    case ARG_SOCKADDR: {
        unsigned long addrlen = (desc->arg_idx >= 0)
            ? (unsigned long)REG_ARG(*regs, desc->arg_idx)
            : 0;
        fmt_sockaddr(tracee, (unsigned long)val, (socklen_t)addrlen, buf, sz);
        break;
    }

    case ARG_STR: {
        char tmp[256];
        if (decode_str(tracee, (unsigned long)val, tmp, sizeof(tmp)) == 0) {
            /* Escape non-printable bytes */
            size_t pos = 0;
            buf[pos++] = '"';
            for (char *p = tmp; *p && pos + 4 < sz; p++) {
                unsigned char c = (unsigned char)*p;
                if (c == '"' || c == '\\') {
                    buf[pos++] = '\\';
                    buf[pos++] = c;
                } else if (c < 0x20 || c == 0x7f) {
                    pos += snprintf(buf + pos, sz - pos, "\\x%02x", c);
                } else {
                    buf[pos++] = c;
                }
            }
            if (pos + 1 < sz) buf[pos++] = '"';
            buf[pos] = '\0';
        } else {
            snprintf(buf, sz, "0x%llx", val);
        }
        break;
    }

    case ARG_FLAGS:
        fmt_flags(buf, sz, val, desc->consts);
        break;

    case ARG_ENUM:
        fmt_enum(buf, sz, val, desc->consts);
        break;
    case ARG_SOCKDOM:
        fmt_enum(buf, sz, val, desc->consts);
        break;
    case ARG_SOCKTYPE:
        fmt_enum(buf, sz, val, desc->consts);
        break;
    
    case ARG_SOCKADDR_OUT:
        if (!is_exit) {
            snprintf(buf, sz, "<pending>");
        } else {
            unsigned long addrlen_ptr = (unsigned long)REG_ARG(*regs, desc->arg_idx);
            socklen_t actual_len = 0;
            decode_mem(tracee, addrlen_ptr, &actual_len, sizeof(actual_len));
            fmt_sockaddr(tracee, (unsigned long)val, actual_len, buf, sz);
        }
        break;
    default:
        snprintf(buf, sz, "0x%llx", val);
        break;
    }
}

/* ══════════════════════════════════════════════════════════════════════
   Whole-line formatter
   ══════════════════════════════════════════════════════════════════════ */
void syscall_format_entry(pid_t tracee, const user_regs_struct *regs,
                          char *buf, size_t sz)
{
    long nr               = (long)REG_SYSCALL(*regs);
    const SyscallDesc *d  = syscall_desc_find(nr);

    // networking should be done on entry and avoid table lookup for socket options 
    if (nr == SYS_setsockopt || nr == SYS_getsockopt) {
        int level   = (int)REG_ARG(*regs, 1);
        int optname = (int)REG_ARG(*regs, 2);

        char level_buf[32], optname_buf[32];
        fmt_enum(level_buf, sizeof(level_buf), level, sockopt_level);

        const NamedConst *optname_table =
            (level == SOL_SOCKET) ? sockopt_name_sol_socket :
            (level == IPPROTO_TCP) ? sockopt_name_tcp :
            NULL; // fallback — просто число

        fmt_enum(optname_buf, sizeof(optname_buf), optname, optname_table);

        snprintf(buf, sz, "%s(%d, %s, %s, ...)", d->name,
                (int)REG_ARG(*regs, 0), level_buf, optname_buf);
        return;
    }

    size_t pos = 0;

    if (!d) {
        pos += snprintf(buf, sz, "syscall_%ld(?)", nr);
        return;
    }

    pos += snprintf(buf + pos, sz - pos, "%s(", d->name);

    for (int i = 0; i < d->argc && pos < sz; i++) {
        char arg_buf[512];
        unsigned long long val = REG_ARG(*regs, i);
        arg_format(arg_buf, sizeof(arg_buf), &d->args[i], val, tracee, regs, false);

        if (d->args[i].kind != ARG_NONE) {
            pos += snprintf(buf + pos, sz - pos,
                            "%s%s", arg_buf, (i + 1 < d->argc) ? ", " : "");
        }
    }

    if (pos < sz) buf[pos++] = ')';
    if (pos < sz) buf[pos]   = '\0';
}


void syscall_format_exit(pid_t tracee, const user_regs_struct *regs,
                          char *entry_line, char *buf, size_t sz)
{
    long nr              = (long)REG_SYSCALL(*regs);
    const SyscallDesc *d = syscall_desc_find(nr);
    long long ret        = (long long)REG_RET(*regs);

    if (!d) {
        snprintf(buf, sz, "%s = %lld", entry_line, ret);
        return;
    }
    char out_sockaddr[128] = "";
    bool has_out_sockaddr = false;

    for (int i = 0; i < d->argc; i++) {
        if (d->args[i].kind == ARG_SOCKADDR_OUT) {
            unsigned long addr_ptr    = (unsigned long)REG_ARG(*regs, i);
            unsigned long addrlen_ptr = (unsigned long)REG_ARG(*regs, d->args[i].arg_idx);

            socklen_t actual_len = 0;
            decode_mem(tracee, addrlen_ptr, &actual_len, sizeof(actual_len));

            fmt_sockaddr(tracee, addr_ptr, actual_len,
                         out_sockaddr, sizeof(out_sockaddr));
            arg_format(out_sockaddr, sizeof(out_sockaddr), &d->args[i], addr_ptr, tracee, regs, true);
            has_out_sockaddr = true;
            break;
        }
    }

    if (has_out_sockaddr) {
        snprintf(buf, sz, "%s [addr=%s] = %lld", entry_line, out_sockaddr, ret);
    } else {
        snprintf(buf, sz, "%s = %lld", entry_line, ret);
    }
}